### ISSUE TITLE
[Create] Dashboard prototype

### ISSUE THREAD

**Issue by adamski201** [adamski201/RailwayTracker#55]
Use streamlit to create a prototype for the dashboard and mock up some data to experiment with how we could present it.

User Story:
- As a developer, a prototype will let me experiment with what is feasible and get a solid picture of what my final product could look like.

**Comment by aribasyeda** [comment]
👮‍♀ @adamski201 Ticket is missing user story and relevant files and the title is missing [Create] at the start

**Comment by aribasyeda** [comment]
@adamski201 Can we close this issue?
