### ISSUE TITLE
[Create] Create a user-facing subscription form

### ISSUE THREAD

**Issue by SaniyaShaikhh** [adamski201/RailwayTracker#71]
## Task Description
- Develop a user interface on streamlit that would allow users to enter their details and their choice of operator to subscribe to.
## User Stories
- As an engineer I want to create a subscription form for users so that they can subscribe to particular operators and receive updates on any incidents. I also want to make sure that they can unsubscribe easily so that users are not receiving alerts if they no longer want to. 
## Relevant Files [If Available]
-

**Comment by aribasyeda** [comment]
@SaniyaShaikhh I believe the ticket falls under [Create]
